[global]

# If false, makes your Streamlit script wide mode by default. If true, makes your Streamlit script use the default (narrow) mode.
wideMode = true

# Controls whether uncaught app exceptions are displayed in the browser. By default, this is set to True and Streamlit displays app exceptions and associated tracebacks in the browser.
showErrorDetails = true

[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
folderWatchBlacklist = ['']

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all validate cookies from each other.
cookieSecret = "a-random-key-appears-here"

# If false, makes your Streamlit script run as a module. If true, makes your Streamlit script run as a script.
runOnSave = false

# The address where the server will listen for client and browser connections.
address = "0.0.0.0"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false